// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package incominghandler represents the exported interface "wasi:http/incoming-handler@0.2.0".
//
// This interface defines a handler of incoming HTTP Requests. It should
// be exported by components which can respond to HTTP Requests.
package incominghandler

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
	"github.com/rajatjindal/wasi-go-sdk/internal/wasi/http/types"
)

// IncomingRequest represents the imported type alias "wasi:http/incoming-handler@0.2.0#incoming-request".
//
// See [types.IncomingRequest] for more information.
type IncomingRequest = types.IncomingRequest

// ResponseOutparam represents the imported type alias "wasi:http/incoming-handler@0.2.0#response-outparam".
//
// See [types.ResponseOutparam] for more information.
type ResponseOutparam = types.ResponseOutparam

// Handle represents the imported function "handle".
//
// This function is invoked with an incoming HTTP Request, and a resource
// `response-outparam` which provides the capability to reply with an HTTP
// Response. The response is sent by calling the `response-outparam.set`
// method, which allows execution to continue after the response has been
// sent. This enables both streaming to the response body, and performing other
// work.
//
// The implementor of this function must write a response to the
// `response-outparam` before returning, or else the caller will respond
// with an error on its behalf.
//
//	handle: func(request: incoming-request, response-out: response-outparam)
//
//go:nosplit
func Handle(request IncomingRequest, responseOut ResponseOutparam) {
	request0 := cm.Reinterpret[uint32](request)
	responseOut0 := cm.Reinterpret[uint32](responseOut)
	wasmimport_Handle((uint32)(request0), (uint32)(responseOut0))
	return
}

// ExportIncomingRequest represents the exported type alias "wasi:http/incoming-handler@0.2.0#incoming-request".
//
// See [types.IncomingRequest] for more information.
type ExportIncomingRequest = types.IncomingRequest

// ExportResponseOutparam represents the exported type alias "wasi:http/incoming-handler@0.2.0#response-outparam".
//
// See [types.ResponseOutparam] for more information.
type ExportResponseOutparam = types.ResponseOutparam
