// Code generated by wit-bindgen-go. DO NOT EDIT.

package incominghandler

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:http@0.2.0".

//go:wasmimport wasi:http/incoming-handler@0.2.0 handle
//go:noescape
func wasmimport_Handle(request0 uint32, responseOut0 uint32)

//go:wasmexport wasi:http/incoming-handler@0.2.0#handle
//export wasi:http/incoming-handler@0.2.0#handle
func wasmexport_Handle(request0 uint32, responseOut0 uint32) {
	request := cm.Reinterpret[ExportIncomingRequest]((uint32)(request0))
	responseOut := cm.Reinterpret[ExportResponseOutparam]((uint32)(responseOut0))
	Exports.Handle(request, responseOut)
	return
}
